# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AZURE_WEBAPP_PACKGE_PATH: '.'
  AZRUE_WEBAPP_NAME: deploygithubdemo
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKGE_PATH }}/myapp'
    
    - name: Deploy
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: ${{ env.AZRUE_WEBAPP_NAME }}
        slot-name: 'development'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKGE_PATH }}/myapp'
