# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AZURE_WEBAPP_PACKGE_PATH: '.'
  AZRUE_WEBAPP_NAME: deploygithubdemo
  
jobs:
  build:
    env:
      BUILD_CONFIG: Release
      DOT_NET_VERSION: 8.0.x
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOT_NET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Print build config
      run: echo "Build Config - $BUILD_CONFIG"
      
    - name: Build
      run: dotnet build --configuration ${{ env.BUILD_CONFIG }}
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKGE_PATH }}/myapp'
    
    - name: Deploy
      uses: Azure/webapps-deploy@v3.0.1
      with:
        app-name: ${{ env.AZRUE_WEBAPP_NAME }}
        slot-name: '${{env.SLOT_NAME}}'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKGE_PATH }}/myapp'
      env: 
        SLOT_NAME: development
